name: Deploy to Google App Engine

steps:
  - name: Build Project (without tests)
    dir: /workspace/rank-system  # 작업 디렉토리 설정
    entrypoint: ./gradlew
    args:
      - clean
      - build
      - -x
      - test

  - name: Deploy to Google App Engine
    dir: /workspace/rank-system/build/libs  # 작업 디렉토리 설정
    entrypoint: java
    args:
      - -jar
      - rank-system-2.0.0-SNAPSHOT.jar
