steps:
  # 1. Git submodule 업데이트
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git submodule update --init --recursive

  # 2. Java 설치
  - name: 'gcr.io/cloud-builders/java'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update -q && \
        apt-get install -y openjdk-17-jdk

  # 3. 프로젝트 빌드 (테스트를 제외한 빌드)
  - name: 'gcr.io/cloud-builders/gradle'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./gradlew clean build -x test
