name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Build Project
        run: ./gradlew clean build
      - name: Deploy Project
        run: java -jar build/libs/rank-system-2.0.0-SNAPSHOT.jar
