name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build React
        run: |
          # Initialize the frontend submodule
          git submodule update --init --recursive

          # Build the frontend
          cd src/main/frontend
          npm install
          npm run build
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          distribution: adopt
      - name: Build Project
        run: ./gradlew clean build
      - name: Deploy Project
        run: java -jar build/libs/rank-system-2.0.0-SNAPSHOT.jar
