name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build React
        run: |
          git submodule update --init --recursive
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          distribution: adopt
      - name: Build Project(without test)
        run: ./gradlew clean build -x test
      - name: Deploy Project
        run: |
          java -jar build/libs/rank-system-2.0.0-SNAPSHOT.jar \
            --spring.datasource.url="${{ secrets.DATABASE_URL }}" \
            --spring.datasource.username="${{ secrets.DATABASE_USERNAME }}" \
            --spring.datasource.password="${{ secrets.DATABASE_PASSWORD }}"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
