name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Build React
        run: |
          git submodule update --init --recursive
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          distribution: adopt
      - name: Build Project(without test)
        run: |
          ./gradlew clean build -x test
      - name: Publish app to Google App Engine
        uses: zxyle/publish-gae-action@v2.3.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ secrets.PROJECT_ID }}
        
